name: 'salesforce'
version: '0.0.1'

require-dbt-version: [">=0.16.0", "<0.17.0"]

models:
    salesforce:
        materialized: table
        base:
            materialized: ephemeral
        intermediate:
            materialized: ephemeral